# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO.xci
# IP: The module: 'CDC_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO.xci
# IP: The module: 'CDC_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/G/OneDrive/2021ss/fpga2021ss/project_1/project_1.srcs/sources_1/ip/CDC_FIFO/CDC_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CDC_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
